# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PaintGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(410, 0, 281, 121))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setGeometry(QtCore.QRect(1630, 0, 291, 121))
        self.toolButton_3.setObjectName("toolButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 130, 1501, 881))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 411, 1021))
        self.listWidget.setObjectName("listWidget")
        self.toolButton_22 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_22.setGeometry(QtCore.QRect(1030, 0, 321, 121))
        self.toolButton_22.setObjectName("toolButton_22")
        self.toolButton_25 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_25.setGeometry(QtCore.QRect(110, 100, 101, 101))
        self.toolButton_25.setObjectName("toolButton_25")
        self.toolButton_26 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_26.setGeometry(QtCore.QRect(110, 270, 101, 101))
        self.toolButton_26.setObjectName("toolButton_26")
        self.toolButton_27 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_27.setGeometry(QtCore.QRect(110, 450, 101, 101))
        self.toolButton_27.setObjectName("toolButton_27")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton.setText(_translate("MainWindow", "保存"))
        self.toolButton_3.setText(_translate("MainWindow", "橡皮"))
        self.label.setText(_translate("MainWindow", "                                            画板"))
        self.toolButton_22.setText(_translate("MainWindow", "颜色"))
        self.toolButton_25.setText(_translate("MainWindow", "画笔颜色1"))
        self.toolButton_26.setText(_translate("MainWindow", "画笔颜色2"))
        self.toolButton_27.setText(_translate("MainWindow", "画笔颜色3"))
