# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceUI_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import src.ui.res_rc
import src.ui.GUI素材库.rsc_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 801)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("#frame\n"
"{\n"
"    background-color: rgb(49, 51, 53);\n"
"    border-radius:30px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("#frame_2\n"
"{\n"
"    background-color: rgb(83, 83, 83);\n"
"    border-top-left-radius:30px;\n"
"    border-top-right-radius:30px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3.addWidget(self.frame_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("QPushButton\n"
"{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    padding-bottom:3px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/最大化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setAutoRepeatDelay(300)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Meau_WT = QtWidgets.QWidget(self.frame_3)
        self.Meau_WT.setGeometry(QtCore.QRect(0, 0, 141, 550))
        self.Meau_WT.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Meau_WT.setStyleSheet("QWidget{\n"
"\n"
"    background-color: rgba(97, 97, 97, 255);\n"
"}\n"
"QPushButton{\n"
"    font: 17pt;\n"
"    color:rgba(200, 200,200, 255);\n"
"    border-left:3px solid rgba(200, 200, 200, 255);\n"
"    border-radius:9px;\n"
"}\n"
"QPushButton:hover{\n"
"    border-left:7px solid #ffd194;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(255, 255, 255, 50), stop:1 rgba(255, 255, 255, 0))\n"
"    }\n"
"QPushButton:pressed{\n"
"    border-left:7px solid #ffd194;\n"
"    background-color:rgba(0,0,0,40);\n"
"    border-bottom-right-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    }")
        self.Meau_WT.setObjectName("Meau_WT")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Meau_WT)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.Meau_WT)
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setMaximumSize(QtCore.QSize(150, 100))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/实物-画笔.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.Meau_WT)
        self.pushButton_5.setMaximumSize(QtCore.QSize(150, 100))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/橡皮,擦除,橡皮擦.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.Meau_WT)
        self.pushButton_6.setMaximumSize(QtCore.QSize(150, 100))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/形状.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_16 = QtWidgets.QPushButton(self.Meau_WT)
        self.pushButton_16.setMaximumSize(QtCore.QSize(150, 100))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/颜色.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon6)
        self.pushButton_16.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_2.addWidget(self.pushButton_16)
        self.pushButton_7 = QtWidgets.QPushButton(self.Meau_WT)
        self.pushButton_7.setMaximumSize(QtCore.QSize(150, 100))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/新建文件.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon7)
        self.pushButton_7.setIconSize(QtCore.QSize(28, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.Meau_WT)
        self.pushButton_8.setMaximumSize(QtCore.QSize(150, 100))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon8)
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.Meau_WT)
        self.pushButton_9.setMaximumSize(QtCore.QSize(150, 100))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon9)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(140, 0, 141, 550))
        self.frame_5.setStyleSheet("QFrame {\n"
"background-color:rgb(145, 145, 145);\n"
"padding-bottom:5px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_5)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 189, 141, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/细线条.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon10)
        self.pushButton_10.setIconSize(QtCore.QSize(50, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/中线条.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon11)
        self.pushButton_11.setIconSize(QtCore.QSize(50, 20))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/粗线条.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon12)
        self.pushButton_12.setIconSize(QtCore.QSize(50, 20))
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_3.addWidget(self.pushButton_12)
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(0, 20, 139, 72))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("QLabel {\n"
"color:rgb(241, 241, 241);\n"
"font-size:24px;\n"
"margin-left:17px;\n"
"margin-top:15px;\n"
"}")
        self.label.setObjectName("label")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_15.setGeometry(QtCore.QRect(0, 0, 139, 30))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"background-color:rgb(145, 145, 145);\n"
"margin-left:10px;\n"
"margin-right:80px;\n"
"border-radius:10px;\n"
"height:30px;\n"
"}")
        self.pushButton_15.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/返回.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon13)
        self.pushButton_15.setObjectName("pushButton_15")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setGeometry(QtCore.QRect(140, 0, 211, 550))
        self.frame_6.setStyleSheet("QFrame {\n"
"background-color:rgb(145, 145, 145);\n"
"padding:5px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_6)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 80, 211, 464))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_22 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"width:80px;\n"
"}")
        self.pushButton_22.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/正方形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_22.setIcon(icon14)
        self.pushButton_22.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_22.setObjectName("pushButton_22")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_22)
        self.pushButton_21 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"width:80px;\n"
"}")
        self.pushButton_21.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/tx-圆形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_21.setIcon(icon15)
        self.pushButton_21.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_21.setObjectName("pushButton_21")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_21)
        self.pushButton_27 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_27.sizePolicy().hasHeightForWidth())
        self.pushButton_27.setSizePolicy(sizePolicy)
        self.pushButton_27.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"width:80px;\n"
"}")
        self.pushButton_27.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/tx-三角形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_27.setIcon(icon16)
        self.pushButton_27.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_27.setObjectName("pushButton_27")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_27)
        self.pushButton_24 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_24.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/tx-五边形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_24.setIcon(icon17)
        self.pushButton_24.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_24.setObjectName("pushButton_24")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_24)
        self.pushButton_29 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_29.sizePolicy().hasHeightForWidth())
        self.pushButton_29.setSizePolicy(sizePolicy)
        self.pushButton_29.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"width:80px;\n"
"}")
        self.pushButton_29.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/tx-六边形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_29.setIcon(icon18)
        self.pushButton_29.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_29.setObjectName("pushButton_29")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_29)
        self.pushButton_23 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_23.sizePolicy().hasHeightForWidth())
        self.pushButton_23.setSizePolicy(sizePolicy)
        self.pushButton_23.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_23.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/tx-长方形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_23.setIcon(icon19)
        self.pushButton_23.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_23.setObjectName("pushButton_23")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_23)
        self.pushButton_30 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_30.sizePolicy().hasHeightForWidth())
        self.pushButton_30.setSizePolicy(sizePolicy)
        self.pushButton_30.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"width:80px;\n"
"}")
        self.pushButton_30.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/tx-梯形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_30.setIcon(icon20)
        self.pushButton_30.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_30.setObjectName("pushButton_30")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton_30)
        self.pushButton_26 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_26.sizePolicy().hasHeightForWidth())
        self.pushButton_26.setSizePolicy(sizePolicy)
        self.pushButton_26.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_26.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/tx-八边形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_26.setIcon(icon21)
        self.pushButton_26.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_26.setObjectName("pushButton_26")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_26)
        self.pushButton_31 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_31.sizePolicy().hasHeightForWidth())
        self.pushButton_31.setSizePolicy(sizePolicy)
        self.pushButton_31.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"width:80px;\n"
"}")
        self.pushButton_31.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/tx-菱形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_31.setIcon(icon22)
        self.pushButton_31.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_31.setObjectName("pushButton_31")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pushButton_31)
        self.pushButton_25 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_25.sizePolicy().hasHeightForWidth())
        self.pushButton_25.setSizePolicy(sizePolicy)
        self.pushButton_25.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_25.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/tx-平行四边形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_25.setIcon(icon23)
        self.pushButton_25.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_25.setObjectName("pushButton_25")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pushButton_25)
        self.pushButton_28 = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_28.sizePolicy().hasHeightForWidth())
        self.pushButton_28.setSizePolicy(sizePolicy)
        self.pushButton_28.setStyleSheet("QPushButton{\n"
"background-color:rgb(242, 242, 242);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_28.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icons/GUI-rsc/tx-六角星形.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_28.setIcon(icon24)
        self.pushButton_28.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_28.setObjectName("pushButton_28")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pushButton_28)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 121, 41))
        self.label_3.setStyleSheet("QLabel {\n"
"color:rgb(241, 241, 241);\n"
"font-size:24px;\n"
"margin-left:30px;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 0, 139, 30))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"background-color:rgb(145, 145, 145);\n"
"margin-left:10px;\n"
"margin-right:80px;\n"
"border-radius:10px;\n"
"height:30px;\n"
"}")
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon13)
        self.pushButton_14.setObjectName("pushButton_14")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setGeometry(QtCore.QRect(140, 0, 141, 550))
        self.frame_8.setStyleSheet("QFrame {\n"
"background-color:rgb(145, 145, 145);\n"
"padding-bottom:5px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_8)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 141, 541))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_13 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"background-color:rgb(145, 145, 145);\n"
"margin-left:10px;\n"
"margin-right:80px;\n"
"border-radius:10px;\n"
"height:30px;\n"
"}")
        self.pushButton_13.setText("")
        self.pushButton_13.setIcon(icon13)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_6.addWidget(self.pushButton_13)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setStyleSheet("QLabel {\n"
"color:rgb(241, 241, 241);\n"
"font-size:24px;\n"
"margin-left:37px;\n"
"margin-top:15px;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.pushButton_60 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_60.sizePolicy().hasHeightForWidth())
        self.pushButton_60.setSizePolicy(sizePolicy)
        self.pushButton_60.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 255, 255);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_60.setObjectName("pushButton_60")
        self.verticalLayout_6.addWidget(self.pushButton_60)
        self.pushButton_62 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_62.sizePolicy().hasHeightForWidth())
        self.pushButton_62.setSizePolicy(sizePolicy)
        self.pushButton_62.setStyleSheet("QPushButton{\n"
"background-color:rgb(0, 170, 255);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_62.setObjectName("pushButton_62")
        self.verticalLayout_6.addWidget(self.pushButton_62)
        self.pushButton_63 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_63.sizePolicy().hasHeightForWidth())
        self.pushButton_63.setSizePolicy(sizePolicy)
        self.pushButton_63.setStyleSheet("QPushButton{\n"
"background-color:rgb(85, 170, 0);\n"
"color:rgb(255, 255, 255);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_63.setObjectName("pushButton_63")
        self.verticalLayout_6.addWidget(self.pushButton_63)
        self.pushButton_64 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_64.sizePolicy().hasHeightForWidth())
        self.pushButton_64.setSizePolicy(sizePolicy)
        self.pushButton_64.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 255, 127);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_64.setObjectName("pushButton_64")
        self.verticalLayout_6.addWidget(self.pushButton_64)
        self.pushButton_65 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_65.sizePolicy().hasHeightForWidth())
        self.pushButton_65.setSizePolicy(sizePolicy)
        self.pushButton_65.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 0, 0);\n"
"color:rgb(255, 255, 255);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_65.setObjectName("pushButton_65")
        self.verticalLayout_6.addWidget(self.pushButton_65)
        self.pushButton_66 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_66.sizePolicy().hasHeightForWidth())
        self.pushButton_66.setSizePolicy(sizePolicy)
        self.pushButton_66.setStyleSheet("QPushButton{\n"
"background-color:rgb(170, 85, 255);\n"
"color:rgb(255, 255, 255);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_66.setObjectName("pushButton_66")
        self.verticalLayout_6.addWidget(self.pushButton_66)
        self.pushButton_67 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_67.sizePolicy().hasHeightForWidth())
        self.pushButton_67.setSizePolicy(sizePolicy)
        self.pushButton_67.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 170, 255);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_67.setObjectName("pushButton_67")
        self.verticalLayout_6.addWidget(self.pushButton_67)
        self.pushButton_68 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_68.sizePolicy().hasHeightForWidth())
        self.pushButton_68.setSizePolicy(sizePolicy)
        self.pushButton_68.setStyleSheet("QPushButton{\n"
"background-color:rgb(0, 85, 255);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_68.setObjectName("pushButton_68")
        self.verticalLayout_6.addWidget(self.pushButton_68)
        self.pushButton_69 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_69.sizePolicy().hasHeightForWidth())
        self.pushButton_69.setSizePolicy(sizePolicy)
        self.pushButton_69.setStyleSheet("QPushButton{\n"
"background-color:rgb(170, 255, 127);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_69.setObjectName("pushButton_69")
        self.verticalLayout_6.addWidget(self.pushButton_69)
        self.pushButton_70 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_70.sizePolicy().hasHeightForWidth())
        self.pushButton_70.setSizePolicy(sizePolicy)
        self.pushButton_70.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 170, 127);\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"border-radius:10px;\n"
"}")
        self.pushButton_70.setObjectName("pushButton_70")
        self.verticalLayout_6.addWidget(self.pushButton_70)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1300, 711))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(1030, 0, 231, 51))
        self.label_4.setStyleSheet("QLabel{\n"
"    font: 17pt;\n"
"    color:rgba(200, 200,200, 255);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_2.raise_()
        self.Meau_WT.raise_()
        self.frame_5.raise_()
        self.frame_6.raise_()
        self.frame_8.raise_()
        self.label_4.raise_()
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionxinjian = QtWidgets.QAction(MainWindow)
        self.actionxinjian.setObjectName("actionxinjian")
        self.actiona = QtWidgets.QAction(MainWindow)
        self.actiona.setObjectName("actiona")
        self.actionbaoqun = QtWidgets.QAction(MainWindow)
        self.actionbaoqun.setObjectName("actionbaoqun")
        self.actionx = QtWidgets.QAction(MainWindow)
        self.actionx.setObjectName("actionx")
        self.actionl = QtWidgets.QAction(MainWindow)
        self.actionl.setObjectName("actionl")
        self.actionbao = QtWidgets.QAction(MainWindow)
        self.actionbao.setObjectName("actionbao")
        self.actionda = QtWidgets.QAction(MainWindow)
        self.actionda.setObjectName("actionda")
        self.actionbao_2 = QtWidgets.QAction(MainWindow)
        self.actionbao_2.setObjectName("actionbao_2")
        self.actionb = QtWidgets.QAction(MainWindow)
        self.actionb.setObjectName("actionb")
        self.actiont = QtWidgets.QAction(MainWindow)
        self.actiont.setObjectName("actiont")
        self.actionshux = QtWidgets.QAction(MainWindow)
        self.actionshux.setObjectName("actionshux")
        self.actiong = QtWidgets.QAction(MainWindow)
        self.actiong.setObjectName("actiong")

        self.retranslateUi(MainWindow)
        self.pushButton_3.clicked.connect(MainWindow.close)
        self.pushButton_2.clicked.connect(MainWindow.showMaximized)
        self.pushButton.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "画笔"))
        self.pushButton_5.setText(_translate("MainWindow", "橡皮"))
        self.pushButton_6.setText(_translate("MainWindow", "形状"))
        self.pushButton_16.setText(_translate("MainWindow", "颜色"))
        self.pushButton_7.setText(_translate("MainWindow", "新建"))
        self.pushButton_8.setText(_translate("MainWindow", "打开"))
        self.pushButton_9.setText(_translate("MainWindow", "保存"))
        self.pushButton_10.setText(_translate("MainWindow", "1 细"))
        self.pushButton_11.setText(_translate("MainWindow", "2 中"))
        self.pushButton_12.setText(_translate("MainWindow", "3 粗"))
        self.label.setText(_translate("MainWindow", "粗细"))
        self.label_3.setText(_translate("MainWindow", "形状"))
        self.label_9.setText(_translate("MainWindow", "颜色"))
        self.pushButton_60.setText(_translate("MainWindow", "1 白色"))
        self.pushButton_62.setText(_translate("MainWindow", "2 蓝色"))
        self.pushButton_63.setText(_translate("MainWindow", "3 绿色"))
        self.pushButton_64.setText(_translate("MainWindow", "4 黄色"))
        self.pushButton_65.setText(_translate("MainWindow", "5 红色"))
        self.pushButton_66.setText(_translate("MainWindow", "6 紫色"))
        self.pushButton_67.setText(_translate("MainWindow", "7 粉色"))
        self.pushButton_68.setText(_translate("MainWindow", "8 深蓝"))
        self.pushButton_69.setText(_translate("MainWindow", "9 嫩绿"))
        self.pushButton_70.setText(_translate("MainWindow", "10 橘色"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "当前选择："))
        self.actionxinjian.setText(_translate("MainWindow", "新建"))
        self.actiona.setText(_translate("MainWindow", "打开"))
        self.actionbaoqun.setText(_translate("MainWindow", "保存"))
        self.actionx.setText(_translate("MainWindow", "图形库"))
        self.actionl.setText(_translate("MainWindow", "另存为"))
        self.actionbao.setText(_translate("MainWindow", "保存全部"))
        self.actionda.setText(_translate("MainWindow", "打印"))
        self.actionbao_2.setText(_translate("MainWindow", "保存图像"))
        self.actionb.setText(_translate("MainWindow", "关闭"))
        self.actiont.setText(_translate("MainWindow", "退出"))
        self.actionshux.setText(_translate("MainWindow", "属性"))
        self.actiong.setText(_translate("MainWindow", "关于画板"))

